### ISSUE TITLE
How did you filter out the missing data?

### ISSUE THREAD

**Issue by harshini-sewani** [lsa-pucrs/acerta-abide#12]
Hello Team,
I really appreciate your work. I just have one question regarding the CSV dataset how did your team filter out missing data? I appreciate your help.

Looking forward to your response.

**Comment by anibalsolon** [comment]
Hi @harshini-sewani 

We used the participants that have values in the fields FILE_ID, DX_GROUP, SEX, and SITE_ID. We dropped the ones which do not.

If you plan to use other columns, such as from assessments, I would recommend checking the original ABIDE dataset publication.

**Comment by harshini-sewani** [comment]
Hi Team,
Thank you so much for the quick response.
