### ISSUE TITLE
Something about prepare_data

### ISSUE THREAD

**Issue by xugaoxu1205** [lsa-pucrs/acerta-abide#14]
![image](https://user-images.githubusercontent.com/62278984/89182075-86808800-d5c7-11ea-8d7f-c46f8e0ef735.png)
I'm sorry to bother you.  When I was running prepare_data I met this problem . I hope you can help me answer it, thank you!!!!!!

**Comment by meneguzzi** [comment]
It seems like you are using Python 2.7, @anibalsolon double check this, but I'm positive we use Python 3. I will update the README to make that clear.
