### ISSUE TITLE
Prepare_data.py

### ISSUE THREAD

**Issue by olahazem** [lsa-pucrs/acerta-abide#20]
Whenever I run prepare_data.py this error occurs.
I have tried adding all the answers of the previous issues about the same file, however it's still not fixed.
Is there any solution to my problem?
![image](https://user-images.githubusercontent.com/76071034/118488922-85ff4b00-b71c-11eb-99b0-ba973f8e3b09.png)

**Comment by meneguzzi** [comment]
@anibalsolon have you seen anything like that?

**Comment by anibalsolon** [comment]
Not really- is that a Windows issue? We never really run it on Windows, only Linux.

**Comment by meneguzzi** [comment]
Yeah, I did not realize this was in Windows, indeed, your best bet might be to install Ubuntu via WSL and try that way.

**Comment by olahazem** [comment]
Thanks a lot for your replies. Yes, I ran the project on windows, I was able to fix this issue and I was gonna write how I fixed it. I installed Tensorflow version 1.15.0 and deleted the HDF5 file (it was created again during run time) and so I was able to prepare the data. Actually I ran the whole project on Windows and got 67% accuracy.
Thank you for your work. @meneguzzi @anibalsolon

**Comment by meneguzzi** [comment]
You are very welcome, if you can make your code parameterizable, and explain the steps for windows in the README, we'd welcome a pull request.

**Comment by olahazem** [comment]
Sure, that would be great. I'll make sure to pull a request soon.
