### ISSUE TITLE
"docker build -t acerta-abide"-Not working

### ISSUE THREAD

**Issue by akshayvijayan** [lsa-pucrs/acerta-abide#7]
The following error occurs while running the docker build. The latest version of tensorflow-gpu is installed.

Sending build context to Docker daemon  1.349GB
Step 1/5 : FROM gcr.io/tensorflow/tensorflow:latest-gpu
manifest for gcr.io/tensorflow/tensorflow:latest-gpu not found

**Comment by vmirly** [comment]
I also have the same issue! There is no gcr.io folder in this repository. Are there some missing files?

**Comment by ShekharDewan** [comment]
This still seems to be an issue.

**Comment by ShekharDewan** [comment]
@meneguzzi Tagging you in case github is not notifying correctly.

**Comment by meneguzzi** [comment]
Hi, I did receive the notification, but at the moment I'm in a conference in Berkeley, so I apologise for not being able to respond in time. @anibalsolon has a lot more experience in docker than I do, if he can jump in, I'd appreciate it.

**Comment by meneguzzi** [comment]
@Siddharth-Shrivastava7 , did your pull request fix this?

**Comment by Siddharth-Shrivastava7** [comment]
No, I haven't used the docker

*Siddharth Shrivastava*

*Senior Undergraduate Student | NIT, Raipur | Electronics and Communication*
*Mobile: +91 9009216654 <9009216654>*
*Skype: live:siddharthamanik16*
*Email: siddharthmanik16@gmail.com <siddharthmanik16@gmail.com>*
*Address: Room no 537, Boys Hostel H, NIT Raipur, G.E. Road, Raipur,
Chhattisgarh, India *
<https://www.linkedin.com/in/siddharth-shrivastava-/>
<https://github.com/Siddharth-Shrivastava7> <https://twitter.com/Sidmanik7>

**Comment by anibalsolon** [comment]
The used image has been updated- Tensorflow was removed from the Google Cloud Registry.

The build process works now.
